# Uncomment the next line to define a global platform for your project
 platform :ios, '12.0'

source 'https://github.com/SumSubstance/Specs.git'
source 'https://cdn.cocoapods.org/'

target 'PayWiserOnboardingKYC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PayWiserOnboardingKYC
  
  pod 'VideoID', '7.1.21'
  pod 'IdensicMobileSDK', '1.18.4'
  pod 'IdensicMobileSDK/Core', '1.18.4'
  pod 'IdensicMobileSDK/Default', '1.18.4'

end
