# Uncomment the next line to define a global platform for your project
 platform :ios, '12.0'

target 'PayWiserOnboardingKYC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PayWiserOnboardingKYC

  pod 'PhoneNumberKit', '3.3.1'
  pod 'CountryPickerView', '3.1.3'
  pod 'VideoID', '7.1.9'

end
